app/controllers/notices_controller.rb, config/routes.rb
=> Remove Notice image

config/environments/production.rb
Changing email configuration to use SendGrid on production
=> SendGrid email configuration

app/controllers/admin/vote_users_controller.rb, app/helpers/vote_user_helper.rb, app/helpers/votes_helper.rb, app/mailers/vote_mailer.rb, app/models/user.rb, app/models/vote.rb, app/models/vote_post.rb, app/services/vote_service.rb, app/views/admin/vote_users/_form.html.erb, app/views/admin/vote_users/edit.html.erb, app/views/admin/vote_users/index.html.erb, app/views/admin/vote_users/show.html.erb, app/views/vote_mailer/votecode.html.erb, app/views/vote_mailer/votecode.text.erb, config/locales/models/vote.sv.yml, config/locales/views/vote_posts.sv.yml, config/locales/views/vote_users.sv.yml, config/routes.rb, spec/controllers/admin/vote_users_controller_spec.rb, spec/factories/shared.rb, spec/factories/vote_posts.rb, spec/factories/votes.rb, spec/helpers/vote_user_helper_spec.rb, spec/models/vote_post_spec.rb, spec/services/vote_service_spec.rb
New votecodes are sent to users
New methods for handling user presence
=> Vote: adding tests and votecode mailing

app/assets/stylesheets/style/forms.scss, app/assets/stylesheets/style/headers.scss, app/controllers/admin/vote_users_controller.rb, app/controllers/admin/votes_controller.rb, app/controllers/vote_posts_controller.rb, app/helpers/votes_helper.rb, app/models/vote_option.rb, app/models/vote_post.rb, app/views/admin/vote_users/show.html.erb, app/views/admin/votes/index.html.erb, app/views/admin/votes/show.html.erb, app/views/vote_posts/new.html.erb, config/locales/views/vote_posts.sv.yml, config/locales/views/votes.sv.yml, config/routes.rb, spec/controllers/admin/vote_users_controller_spec.rb, spec/controllers/admin/votes_controller_spec.rb, spec/controllers/vote_posts_controller_spec.rb, spec/features/confirm_account_spec.rb, spec/features/login_spec.rb, spec/features/sign_up_spec.rb, spec/features/votes_spec.rb, spec/models/vote_post_spec.rb, spec/page_objects/login_page.rb
Tests:
- VoteUser
- Vote
- Sign up, sign in, confirm account
Changing size of header-tags
=> Specs: more controller and feature tests

app/assets/stylesheets/partials/vote_users.scss, app/controllers/admin/vote_users_controller.rb, app/helpers/vote_user_helper.rb, app/models/permission_user.rb, app/models/user.rb, app/services/user_service.rb, app/views/admin/vote_users/index.html.erb, app/views/admin/vote_users/show.html.erb, config/locales/views/users.sv.yml, config/locales/views/vote_users.sv.yml, spec/controllers/admin/documents_controller_spec.rb, spec/controllers/admin/vote_users_controller_spec.rb, spec/controllers/admin/votes_controller_spec.rb, spec/factories/permission_users.rb, spec/factories/permissions.rb, spec/factories/users.rb, spec/models/permission_user_spec.rb, spec/models/user_spec.rb
Require confirmation through validations
Reworking factories
Fixing #37
=> Require confirmation to adjust and send votecode

app/assets/stylesheets/partials/_vote_users.scss, app/assets/stylesheets/partials/vote_users.scss, app/controllers/admin/vote_users_controller.rb, app/helpers/vote_user_helper.rb, app/views/admin/vote_users/index.html.erb, app/views/admin/vote_users/new_votecode.js.erb, app/views/admin/vote_users/not_present.js.erb, app/views/admin/vote_users/present.js.erb, app/views/layouts/_content.html.erb, config/locales/views/vote_users.sv.yml, spec/controllers/admin/vote_users_controller_spec.rb
Adding remote buttons for admin interface for adjusting and sending new
votecodes
=> Remote buttons: adjusting and votecode

app/views/admin/votes/show.html.erb, app/views/vote_posts/new.html.erb, config/locales/models/user.sv.yml, config/locales/models/vote_post.sv.yml, config/locales/models/vote_user.sv.yml, config/locales/views/vote_posts.sv.yml, config/locales/views/vote_users.sv.yml, db/migrate/20160312184600_vote_default_closed.rb, db/schema.rb
Fixes #39, #44, #46, #47 and #48
=> Small fixes

app/controllers/admin/agendas_controller.rb, app/helpers/agendas_helper.rb, app/views/admin/agendas/index.html.erb, app/views/admin/agendas/set_closed.js.erb, app/views/admin/agendas/set_current.js.erb, config/locales/views/agenda.sv.yml, db/seeds.rb, spec/controllers/admin/agendas_controller_spec.rb, spec/factories/agenda.rb
Adding a `rake db:seed` for Agenda
Adding remote actions for admin interface
#50
=> Agenda: seeding data, remote button

app/assets/javascripts/application.js, app/controllers/admin/adjustments_controller.rb, app/controllers/admin/vote_users_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/admin/adjustments/index.html.erb, app/views/admin/vote_users/_search_row.html.erb, app/views/admin/vote_users/_search_row_header.html.erb, app/views/admin/vote_users/index.html.erb, app/views/admin/vote_users/search.js.erb, app/views/users/_form.html.erb, config/locales/models/user.sv.yml, config/locales/views/adjustment.sv.yml, config/routes.rb, db/migrate/20160316180136_add_card_number_to_user.rb, db/schema.rb, spec/controllers/admin/adjustments_controller_spec.rb, spec/controllers/admin/vote_users_controller_spec.rb, spec/factories/adjustment.rb, spec/models/user_spec.rb, vendor/assets/javascripts/inputmask.js
Adding card_number field to user
Adding index with remote form for searching with magnetic card reader
Using inputmask to proper format the field
=> User: Card number for adjusting of users

app/assets/javascripts/application.js, app/assets/javascripts/vote_status_refresh.js, app/assets/stylesheets/partials/_votes.scss, app/controllers/admin/adjustments_controller.rb, app/controllers/admin/vote_users_controller.rb, app/controllers/admin/votes_controller.rb, app/view_objects/vote_status_view.rb, app/views/admin/adjustments/index.html.erb, app/views/admin/vote_users/index.html.erb, app/views/admin/vote_users/not_present.js.erb, app/views/admin/vote_users/present.js.erb, app/views/admin/votes/_status.html.erb, app/views/admin/votes/refresh.js.erb, config/locales/views/agenda.sv.yml, config/locales/views/default.sv.yml, config/locales/views/vote_users.sv.yml, config/locales/views/votes.sv.yml, config/routes.rb, spec/controllers/admin/adjustments_controller_spec.rb, spec/view_objects/vote_status_view_spec.rb
Adding javascript to refresh adjustment count, current agenda and current vote
on adjustment index view.
Updating the presence-column on adjustment.
=> Adjustment view: adding current status of voting

app/helpers/votes_helper.rb, app/models/audit.rb, app/models/vote_option.rb, app/views/admin/votes/show.html.erb, config/locales/views/votes.sv.yml
=> Deleting vote options

app/assets/stylesheets/partials/_votes.scss, app/controllers/admin/votes_controller.rb, app/controllers/votes_controller.rb, app/helpers/votes_helper.rb, app/models/agenda.rb, app/models/vote.rb, app/models/vote_option.rb, app/models/vote_post.rb, app/services/vote_service.rb, app/view_objects/vote_status_view.rb, app/views/admin/votes/_form.html.erb, app/views/admin/votes/edit.html.erb, app/views/admin/votes/index.html.erb, app/views/admin/votes/new.html.erb, app/views/admin/votes/show.html.erb, app/views/votes/index.html.erb, config/locales/models/vote.sv.yml, config/locales/views/agenda.sv.yml, config/locales/views/votes.sv.yml, db/migrate/20160319161418_add_agenda_to_vote.rb, db/migrate/20160320125754_add_selected_to_vote_post.rb, db/schema.rb, spec/features/votes_spec.rb, spec/services/vote_service_spec.rb
Adding some visuals to User views
Adding Agenda reference to Vote
Adding :selected to VotePost
=> Connect Vote to Agenda

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/update_adjustment_row_order.js.coffee, app/assets/stylesheets/partials/_vote_users.scss, app/controllers/admin/adjustments_controller.rb, app/controllers/admin/vote_users_controller.rb, app/models/adjustment.rb, app/views/admin/adjustments/edit.html.erb, app/views/admin/vote_users/_adjustments.html.erb, app/views/admin/vote_users/_log.html.erb, app/views/admin/vote_users/attendance_list.html.erb, app/views/admin/vote_users/show.html.erb, config/routes.rb, db/migrate/20160323231142_add_row_order_to_adjustment.rb, db/schema.rb, spec/controllers/admin/adjustments_controller_spec.rb, spec/models/adjustment_spec.rb
Allows you to order the adjustments for a user using drag and drop :open_mouth:
Sorry for much JS/Coffe code :cry: 
Is it possible to add internationalization to JS?
=> Ordering Adjustments

app/controllers/admin/adjustments_controller.rb, app/controllers/admin/agendas_controller.rb, app/controllers/admin/base_controller.rb, app/controllers/admin/documents_controller.rb, app/controllers/admin/menus_controller.rb, app/controllers/admin/news_controller.rb, app/controllers/admin/permission_users_controller.rb, app/controllers/admin/users_controller.rb, app/controllers/admin/vote_users_controller.rb, app/controllers/admin/votes_controller.rb, app/models/ability.rb, app/models/admin_ability.rb, app/models/permission.rb, app/views/admin/permission_users/_form.html.erb, app/views/layouts/_menu.html.erb, app/views/layouts/_topbar.html.erb, lib/tasks/permissions.rake, spec/controllers/admin/vote_users_controller_spec.rb, spec/controllers/static_pages_controller_spec.rb, spec/lib/tasks/promote_admin_spec.rb
Adding a base controller for loading admin permissions
Moving all admin controllers to use Cancancan properly
=> Creating AdminPermission

Gemfile, Gemfile.lock, config/initializers/rollbar.rb
Sets up https://rollbar.com to track the web application.
=> Rollbar: issue tracking

app/controllers/static_pages_controller.rb, app/mailers/contact_mailer.rb, app/models/ability.rb, app/views/devise/registrations/new.html.erb, app/views/layouts/_copyright.html.erb, app/views/static_pages/about.html.erb, app/views/static_pages/terms.html.erb, config/locales/views/about.sv.yml, config/locales/views/default.sv.yml, config/locales/views/terms.sv.yml, config/locales/views/users.sv.yml, config/routes.rb, db/seeds.rb, public/404.html, public/422.html, public/500.html
Add a terms of service for users
=> Terms of Service

app/controllers/admin/vote_users_controller.rb, app/helpers/adjustments_helper.rb, app/models/agenda.rb, app/views/admin/vote_users/_attendance_grid.html.erb, app/views/admin/vote_users/attendance_list.html.erb
Adds '[DELETED]' to adjustments in the list that belong to deleted agendas
Enables CSV export for the attendance list
=> Updating attendance list

app/assets/javascripts/google_analytics.js, app/views/layouts/_google_analytics.html.erb, app/views/layouts/application.html.erb
Using an environmental variable for storing the tracking code.
=> Google Analytics: adding more statistics tracking

Gemfile, Gemfile.lock, app/controllers/admin/agendas_controller.rb, app/models/agenda.rb, app/view_objects/start_page.rb, app/views/static_pages/index.html.erb, app/views/users/_form.html.erb, config/environments/development.rb, lib/tasks/tests_data.rake
Adding Bullet to notify on N+1
Adding full path to Mecenat image
=> Fixing N+1 and view fixes

app/assets/stylesheets/partials/_votes.scss, app/assets/stylesheets/style/headers.scss, app/controllers/admin/votes_controller.rb, app/helpers/vote_user_helper.rb, app/helpers/votes_helper.rb, app/models/vote.rb, app/view_objects/vote_status_view.rb, app/views/admin/votes/_audits.html.erb, app/views/admin/votes/edit.html.erb, app/views/admin/votes/refresh_count.js.erb, app/views/admin/votes/show.html.erb, app/views/users/_confirm_information.html.erb, app/views/votes/index.html.erb, config/locales/models/audit.sv.yml, config/locales/views/votes.sv.yml, config/routes.rb, spec/controllers/admin/votes_controller_spec.rb
Adding more disposition and current vote status
Adding refresh action for amount of votes
=> Admin vote page: new look

app/assets/stylesheets/partials/_adjustments.scss, app/assets/stylesheets/partials/_users.scss, app/assets/stylesheets/style/navbar.scss, app/helpers/vote_user_helper.rb, app/views/admin/users/index.html.erb, app/views/admin/vote_users/_search_row.html.erb, app/views/admin/votes/index.html.erb, app/views/agendas/_start_page.html.erb, app/views/contacts/index.html.erb, app/views/static_pages/index.html.erb, app/views/users/_confirm_information.html.erb, config/locales/views/users.sv.yml, config/locales/views/votes.sv.yml
* On the "quick adjustment" page, present users get the orange background
* Displays a card next to the names of those who have added their mecenat card number (in the admin/user and admin/vote_user list)
* Changing some font sizes (I think the titles on the front page are too large)
* Other small changes
=> Small view fixes

app/controllers/admin/contacts_controller.rb, app/views/static_pages/about.html.erb, spec/controllers/admin/contacts_controller_spec.rb, spec/features/visit_spec.rb
Adding feature spec for static pages
Fixing typo in view code
=> Fixing About-page error

app/assets/javascripts/vote_status_refresh.js, app/views/admin/adjustments/index.html.erb, app/views/admin/vote_users/index.html.erb, app/views/admin/votes/show.html.erb
Adding data-position to the div in order to make them depend on
which page it was loaded on
Fixing #99
=> Javascript refresh: fix double loading

app/helpers/vote_user_helper.rb, app/views/admin/vote_users/_search_row.html.erb, app/views/admin/vote_users/index.html.erb, app/views/admin/vote_users/new_votecode.js.erb
=> Show if a user has a votecode or not

app/models/user.rb, spec/models/user_spec.rb
=> User: allow LUCAT for student id

app/assets/stylesheets/partials/_adjustments.scss, app/assets/stylesheets/partials/_admin_grid.scss, app/assets/stylesheets/partials/_agendas.scss, app/assets/stylesheets/partials/_vote_users.scss, app/helpers/votes_helper.rb, app/models/vote_post.rb, app/services/vote_service.rb, app/views/admin/adjustments/_info.html.erb, app/views/admin/adjustments/index.html.erb, app/views/admin/agendas/index.html.erb, app/views/admin/agendas/set_closed.js.erb, app/views/admin/agendas/set_current.js.erb, app/views/admin/vote_users/_search_row.html.erb, app/views/admin/vote_users/index.html.erb, app/views/admin/vote_users/not_present.js.erb, app/views/admin/vote_users/present.js.erb, app/views/admin/vote_users/show.html.erb, app/views/admin/votes/index.html.erb, config/locales/models/vote.sv.yml, config/locales/views/adjustment.sv.yml, config/locales/views/vote_users.sv.yml, spec/controllers/vote_posts_controller_spec.rb, spec/models/vote_post_spec.rb, spec/services/vote_service_spec.rb
* Allows blank vote posts (that is, without any vote_option_ids) to be created
* Simple majority is now used instead of qualified majority
* Some useful information for adjusters is added
* Non-working links from ``admin/vote_user#show`` are removed
=> Blank votes and simple majority

app/views/admin/agendas/index.html.erb
Fixes a stupid bug that broke `admin/agenda#index`
=> Agenda grid

app/controllers/documents_controller.rb, app/models/document.rb
- Found a breaking space in document-model.
- Based on issue #140 and some detected errors
=> Documents: check if url exists before reading

app/services/vote_service.rb
Will only allow one person to update at a time
=> VoteOption: lock! when incrementing count

app/services/vote_service.rb, app/views/admin/votes/show.html.erb, config/locales/views/votes.sv.yml
* Adds atomic increment to avoid problems with concurrent votes
* Adds stats for simple majority and 2/3 majority in the admin view
=> Atomic increment

app/views/admin/adjustments/index.html.erb, app/views/admin/agendas/index.html.erb, app/views/admin/vote_users/attendance_list.html.erb, app/views/admin/votes/index.html.erb, app/views/documents/index.html.erb, app/views/news/_news.html.erb, app/views/news/show.html.erb
- Adds edit link to documents
Issue #112
=> Admin permissions: update from can_administrate

config/initializers/filter_parameter_logging.rb
Adding `password_confirmation` again.
=> Filter password_confirmation again

app/views/layouts/email.html.erb
=> Votecode mailer

spec/mailers/application_mailer_spec.rb, spec/mailers/message_mailer_spec.rb, spec/mailers/vote_mailer_spec.rb
- Catches if there is no yield in the layout!
=> Mailers: adds specs

config/locales/views/attendances.sv.yml
=> Translations for attendances

app/controllers/admin/current_items_controller.rb, app/helpers/items_helper.rb, app/models/item.rb, app/models/sub_item.rb, app/views/admin/current_items/destroy.js.erb, app/views/admin/current_items/update.js.erb, app/views/admin/items/edit.html.erb, app/views/admin/sub_items/_table.html.erb, config/locales/models/sub_item.sv.yml, config/locales/views_controllers/items.sv.yml, config/locales/views_controllers/sub_items.sv.yml, config/routes.rb, db/migrate/20180104100302_sub_items_unique_current.rb, db/schema.rb, spec/requests/admin/handle_current_item_spec.rb
- Adds js actions to set current_item
- Adds error messages
- Adds database constraint for one current
=> Beginning work on setting current item

bin/bundle, bin/rails, bin/rake, bin/yarn, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/application_controller_renderer.rb, config/initializers/assets.rb, config/initializers/new_framework_defaults_5_1.rb, config/puma.rb
- Previously not running on 5.1 defaults
=> Rails 5.1: run update command

config/initializers/devise.rb, config/storage.yml
- We do not want to share e.g. Amazon with separate deploys.
=> Stop using Encrypted secrets

app/models/user.rb, app/views/admin/users/_form.html.erb, app/views/admin/users/edit.html.erb, spec/requests/admin/handle_users_spec.rb
=> Users: allow_blank on card number

app/assets/stylesheets/style/admin_grid.scss, app/controllers/admin/attendances_controller.rb, app/services/vote_service.rb, app/views/admin/adjustments/index.html.erb, app/views/admin/attendances/_errors.html.erb, app/views/admin/attendances/destroy.js.erb, app/views/admin/attendances/error.js.erb, app/views/admin/attendances/success.js.erb, app/views/admin/attendances/update.js.erb, config/locales/models/user.sv.yml, config/locales/models/vote.sv.yml, config/locales/views_controllers/attendances.sv.yml, spec/services/vote_service_spec.rb
- Also sends votecodes if needed
=> Adjustment: adds error messages

app/controllers/admin/users_controller.rb, app/models/user.rb, app/views/admin/users/edit.html.erb, app/views/admin/users/index.html.erb, config/locales/views_controllers/users.sv.yml, config/routes.rb, db/migrate/20180209100453_change_unique_email_to_allow_deleting_users.rb, db/migrate/20180209100515_users_devise_remove_trackable.rb, db/schema.rb, spec/requests/admin/handle_users_spec.rb
- Changes unique index to allow registering with same email after
soft-delete.
- Remove Devise Trackable from users - never used for anything.
=> Users: allow soft-deletion and confirmation resend

app/views/items/_votes.html.erb, config/locales/views_controllers/items.sv.yml
=> Votes: require login

app/assets/javascripts/vote_status_refresh.js, app/views/admin/votes/index.html.erb
- Added .js on the url to force the format.
=> Refreshes with javascript

lib/tasks/cleanup.rake, spec/services/cleanup_spec.rb
Fixes #161, need to add it as a button too.
=> Reset: set votecodes to nil
